'''
pr_ci_report.py

Helper script for Pull Request CI Report GitHub Actions workflow
Ingests JSON artifacts containing job results and produces a markdown document with the generated result comment
'''

# Import external dependencies
import glob, json

# Define constant icons for pass/partial pass/fail
ICON_PASS = '✅'
ICON_PARTIAL = '⚠️'
ICON_FAIL = '❌'

# load: given a glob pattern, read all matching JSON files into items and return
def load(pattern):
    items = []
    for f in glob.glob(pattern):
        with open(f) as fh:
            items.append(json.load(fh))
    return items

# os_key: given an item, return the os_name and os_ver variables (for operating system name/version)
def os_key(item):
    return (item.get('os_name', 'Unknown'), item.get('os_ver', 'unknown'))

# summary_icon: given passed and total jobs, return a summary icon depending on proportion of passed jobs
def summary_icon(passed, total):
    if total == 0:
        return 'n/a'
    if passed == total:
        return ICON_PASS
    if passed == 0:
        return ICON_FAIL
    return ICON_PARTIAL

# load Python and R test results
py = load("results/python/**/result.json")
r = load("results/r/**/result.json")

# extract all OS keys and sort in descending order
os_keys = sorted(set(os_key(i) for i in py) | set(os_key(i) for i in r), reverse=True)

# extract all Python versions and sort in ascending order
python_versions = sorted(set(i['python_version'] for i in py), reverse=False)

# extract all R versions and sort in ascending order
r_versions = sorted(set(i['r_version'] for i in r), reverse=False)


# build summary comment as list of lines
lines = []
lines.append('# Pull Request CI Report')

# add caution alert about Crux/TRFP tests to comment
lines.append('')
lines.append('> [!CAUTION]')
lines.append('> GitHub Actions runners do not have ThermoRawFileParser or Crux installed. Tests dependent on these binaries are skipped and should instead be run manually before merging.')

# add summary to comment
lines.append('')
lines.append('<br>')
lines.append('')
lines.append('## Summary')
lines.append('')
lines.append('Operating System | Source distributions built? | CLI available? | Passed Python tests? | Passed R tests?')
lines.append('--|--|--|--|--')
for name, ver in os_keys:
    py_cells = [i for i in py if os_key(i) == (name, ver)]
    r_cells = [i for i in r if os_key(i) == (name, ver)]
    build_ok = len(py_cells) > 0 and all(c['build'] == 'pass' for c in py_cells)
    cli_ok = len(py_cells) > 0 and all(c['cli'] == 'pass' for c in py_cells)
    py_passed = sum(1 for c in py_cells if c['tests'] == 'pass')
    r_passed = sum(1 for c in r_cells if c['tests'] == 'pass')
    build_icon = ICON_PASS if build_ok else ICON_FAIL
    cli_icon = ICON_PASS if cli_ok else ICON_FAIL
    lines.append(f'{name} ({ver}) | {build_icon} | {cli_icon} | {summary_icon(py_passed, len(py_cells))} | {summary_icon(r_passed, len(r_cells))}')

# add Python test results to comment
lines.append('')
lines.append('<br>')
lines.append('')
lines.append('## Python Tests')
lines.append('')
lines.append(f'Python versions tested: {", ".join(python_versions) if python_versions else "none"}')
if python_versions:
    lines.append('')
    lines.append(' Operating System | ' + ' | '.join(f'Python {v}' for v in python_versions))
    lines.append('-- |' * (len(python_versions) + 1))
    for name, ver in os_keys:
        row = [f'{name} ({ver})']
        for v in python_versions:
            match = next(
                (result for result in py if os_key(result) == (name, ver) and result['python_version'] == v),
                None,
            )
            row.append('n/a' if match is None else (ICON_PASS if match['tests'] == 'pass' else ICON_FAIL))
        lines.append(' | '.join(row))

# add R test results to comment
lines.append('')
lines.append('<br>')
lines.append('')
lines.append('## R Tests')
lines.append('')
lines.append(f'R versions tested: {", ".join(r_versions) if r_versions else "none"}')
if r_versions:
    lines.append('')
    lines.append(' Operating System | ' + ' | '.join(f'R {v}' for v in r_versions))
    lines.append('-- |' * (len(r_versions) + 1))
    for name, ver in os_keys:
        row = [f'{name} ({ver})']
        for v in r_versions:
            match = next(
                (result for result in r if os_key(result) == (name, ver) and result['r_version'] == v),
                None,
            )
            row.append('n/a' if match is None else (ICON_PASS if match['tests'] == 'pass' else ICON_FAIL))
        lines.append(' | '.join(row))

# add footer to comment
lines.append('')
lines.append('<br>')
lines.append('')
lines.append('---')
lines.append('_Auto-generated by the comMS Pull Request CI Report workflow. See full logs in the Actions run for this PR._')

# write comment to markdown file
with open('pr_ci_report.md', 'w') as f:
    f.write('\n'.join(lines))