'''
comMS wrapper around Crux binary
'''

# -- Import external dependencies
import contextlib, shutil, subprocess, tempfile
from pathlib import Path
from typing import Optional

# -- Import internal functions
from comms.utils.log import logMsg
from comms.utils.settings import resolvedModifications

# -- Define context manager _cleanBinaryFasta to move binary FASTA files generated by Crux
@contextlib.contextmanager
def _cleanBinaryFasta(dest_dir: Path):
    '''
    Context manager that moves any *-binary-fasta files written to CWD
    during a Crux call into dest_dir afterwards.
    '''
    before = set(Path.cwd().glob('*-binary-fasta'))
    try:
        yield
    finally:
        after = set(Path.cwd().glob('*-binary-fasta'))
        for f in after - before:
            shutil.move(str(f), str(dest_dir / f.name))

# -- _concatPsmFiles: concatenate PSM files, keeping header from first file only
def _concatPsmFiles(psm_files: list[Path], dest: Path) -> None:
    '''
    Concatenate tab-delimited Percolator PSM files into a single file at dest,
    preserving the header from the first file and stripping headers from the rest.
    '''
    with dest.open('w') as out:
        for i, psm_file in enumerate(psm_files):
            with psm_file.open('r') as f:
                for j, line in enumerate(f):
                    if j == 0 and i > 0:
                        continue  # skip header for all but first file
                    out.write(line)

# -- findCrux: returns a Path to the Crux binary under bin_dir/crux*/bin/crux, or None if not found
def findCrux(bin_dir: Path) -> Optional[Path]:
    logMsg.debug(f'Searching for Crux binary under: {bin_dir}')
    matches = list(bin_dir.glob('crux*/bin/crux'))
    if not matches:
        logMsg.warn(f'No Crux binary found under: {bin_dir}')
        return None
    result = sorted(matches)[-1]
    logMsg.debug(f'Crux binary found: {result}')
    return result

# -- runCrux: returns True if the Crux subcommand completed successfully, False on failure
def runCrux(crux_bin: Path, subcommand: str, args: list) -> bool:
    cmd = [str(crux_bin), subcommand] + [str(a) for a in args]
    logMsg.debug(f'Running {subcommand}: {" ".join(cmd)}')
    try:
        result = subprocess.run(cmd, check=False)
        if result.returncode != 0:
            logMsg.warn(f'{subcommand} exited with non-zero return code: {result.returncode}')
            return False
        return True
    except Exception as e:
        logMsg.error(f'Unexpected error running {subcommand}: {e}')
        return False

# -- tideIndex: returns True if the Tide peptide index was built successfully, False on failure
def tideIndex(crux_bin: Path, database: Path, index_dir: Path, config: dict) -> bool:
    logMsg.debug(f'Starting tide-index for database: {database.name}')
    args = [
        '--verbosity', '40',
        '--memory-limit', '8',
        '--enzyme', 'trypsin',
        '--digestion', 'full-digest',
        '--missed-cleavages', str(config['index']['missed_cleavages']),
        '--mods-spec', resolvedModifications(config),
        '--nterm-peptide-mods-spec', config['index']['nterm_peptide_mods_spec'],
        '--nterm-protein-mods-spec', config['index']['nterm_protein_mods_spec'],
        '--decoy-format', 'peptide-reverse',
        '--num-decoys-per-target', '1',
        '--allow-dups', 'T',
        '--clip-nterm-methionine', _tomlToCrux(config['index']['clip_n_met']),
        '--output-dir', str(index_dir),
        '--overwrite', 'T',
        str(database),
        str(index_dir),
    ]
    with _cleanBinaryFasta(index_dir):
        return runCrux(crux_bin, 'tide-index', args)

# -- paramMedic: returns True if param-medic completed successfully, False on failure
def paramMedic(crux_bin: Path, mzml_file: Path, out_dir: Path) -> bool:
    logMsg.debug(f'Running param-medic on: {mzml_file.name}')
    args = [
        '--verbosity', '40',
        '--output-dir', str(out_dir),
        str(mzml_file),
    ]
    return runCrux(crux_bin, 'param-medic', args)

# -- tideSearch: returns True if Tide-search completed successfully for the given mzML file, False on failure
def tideSearch(crux_bin: Path, mzml_file: Path, index_dir: Path, out_dir: Path, fileroot: str, config: dict, threads, precursor_tol=None, mz_bin_width=None) -> bool:
    logMsg.debug(f'Starting tide-search for: {mzml_file.name}')
    prec = precursor_tol or config['search']['precursor_tolerance_ppm']
    bin_width = mz_bin_width  or config['search']['mz_bin_width']
    logMsg.debug(f'Using precursor tolerance: {prec} ppm, m/z bin width: {bin_width}')
    args = [
        '--verbosity', '40',
        '--num-threads', threads,
        '--spectrum-parser', 'pwiz',
        '--precursor-window', str(prec),
        '--precursor-window-type', 'ppm',
        '--mz-bin-width', str(bin_width),
        '--score-function', config['search']['score_function'],
        '--min-peaks', str(config['search']['min_peaks']),
        '--missed-cleavages', str(config['index']['missed_cleavages']),
        '--output-dir', str(out_dir),
        '--fileroot', fileroot,
        '--overwrite', 'T',
        str(mzml_file),
        str(index_dir),
    ]
    return runCrux(crux_bin, 'tide-search', args)

# -- percolator: returns True if Percolator rescoring completed successfully, False on failure
def percolator(crux_bin:Path, target_psm_file: Path, database: Path, out_dir: Path, fileroot: str, config: dict) -> bool:
    logMsg.debug(f'Starting Percolator for: {target_psm_file.name}')
    args = [
        '--verbosity', '40',
        '--protein-enzyme', config['percolator']['protein_enzyme'],
        '--spectral-counting-fdr', str(config['percolator']['psm_fdr']),
        '--output-dir', str(out_dir),
        '--fileroot', fileroot,
        '--overwrite', 'T',
        str(target_psm_file),
    ]
    if config['percolator']['picked_protein']:
        args = ['--picked-protein', str(database)] + args
    return runCrux(crux_bin, 'percolator', args)

# -- spectralCounts: returns True if dNSAF spectral counting completed successfully, False on failure
def spectralCounts(crux_bin: Path, psm_file: Path, database: Path, out_dir: Path, fileroot: str, config: dict) -> bool:
    logMsg.debug(f'Starting spectral-counts for: {psm_file.name}')
    args = [
        '--verbosity', '40',
        '--measure', config['quantify']['measure'],
        '--threshold', str(config['quantify']['qvalue_threshold']),
        '--threshold-type', 'qvalue',
        '--unique-mapping', _tomlToCrux(config['quantify']['unique_mapping']),
        '--protein-database', str(database),
        '--output-dir', str(out_dir),
        '--fileroot', fileroot,
        '--overwrite', 'T',
        str(psm_file),
    ]
    with _cleanBinaryFasta(out_dir):
        return runCrux(crux_bin, 'spectral-counts', args)

# -- lfq: returns True if LFQ quantification completed successfully, False on failure
def lfq(crux_bin: Path, psm_files: list[Path], mzml_dir: Path, out_dir: Path, fileroot: str, config: dict) -> bool:
    logMsg.debug(f'Starting label-free quantification for {len(psm_files)} PSM file(s)')
    # Resolve mzML files by matching stems to PSM file stems
    mzml_files = []
    for psm_file in psm_files:
        stem = psm_file.name.removesuffix('.percolator.target.psms.txt')
        matches = list(mzml_dir.glob(f'{stem}.mzML')) + list(mzml_dir.glob(f'{stem}.mzML.gz'))
        if not matches:
            logMsg.warn(f'No mzML file found for PSM file: {psm_file.name} — skipping')
            continue
        mzml_files.append(matches[0])
    if not mzml_files:
        logMsg.warn('No mzML files could be matched to PSM files — aborting LFQ')
        return False
    logMsg.debug(f'Matched {len(mzml_files)} mzML file(s) for LFQ')
    # Concatenate all PSM files for this fraction into a single temp file
    tmp_psm = out_dir / f'{fileroot}.combined.percolator.target.psms.txt'
    logMsg.debug(f'Concatenating {len(psm_files)} PSM file(s) into: {tmp_psm.name}')
    _concatPsmFiles(psm_files, tmp_psm)
    args = [
        '--verbosity', '40',
        '--output-dir', str(out_dir),
        '--fileroot', fileroot,
        '--overwrite', 'T',
        '--use-shared-peptides-for-protein-quant', 'T',
        '--psm-file-format', 'percolator',
        '--mods-spec', resolvedModifications(config),
        '--nterm-peptide-mods-spec', config['index']['nterm_peptide_mods_spec'],
        '--num-threads', str(config['search']['threads']),
        str(tmp_psm),
    ]
    args += [str(f) for f in mzml_files]
    ok = runCrux(crux_bin, 'lfq', args)
    # Clean up temp PSM file
    try:
        tmp_psm.unlink()
    except OSError as e:
        logMsg.warn(f'Could not remove temporary PSM file {tmp_psm.name}: {e}')
    return ok

# -- _tomlToCrux: helper function returning 'T' if True and 'F' if False
def _tomlToCrux(val: bool):
    if val:
        return 'T' 
    else:
        return 'F'