'''
comMS wrapper around Crux binary
'''

# -- Import external dependencies
import contextlib, shutil, subprocess
from pathlib import Path
from typing import Optional

# -- Import internal functions
from comms.utils.log import logMsg

# -- Define context manager _cleanBinaryFasta to move binary FASTA files generated by Crux
@contextlib.contextmanager
def _cleanBinaryFasta(dest_dir: Path):
    '''
    Context manager that moves any *-binary-fasta files written to CWD
    during a Crux call into dest_dir afterwards.
    '''
    before = set(Path.cwd().glob('*-binary-fasta'))
    try:
        yield
    finally:
        after = set(Path.cwd().glob('*-binary-fasta'))
        for f in after - before:
            shutil.move(str(f), str(dest_dir / f.name))

# -- findCrux: returns a Path to the Crux binary under bin_dir/crux*/bin/crux, or None if not found
def findCrux(bin_dir: Path) -> Optional[Path]:
    logMsg.debug(f'Searching for Crux binary under: {bin_dir}')
    matches = list(bin_dir.glob('crux*/bin/crux'))
    if not matches:
        logMsg.warn(f'No Crux binary found under: {bin_dir}')
        return None
    result = sorted(matches)[-1]
    logMsg.debug(f'Crux binary found: {result}')
    return result

# -- runCrux: returns True if the Crux subcommand completed successfully, False on failure
def runCrux(crux_bin: Path, subcommand: str, args: list) -> bool:
    cmd = [str(crux_bin), subcommand] + [str(a) for a in args]
    logMsg.debug(f'Running {subcommand}: {" ".join(cmd)}')
    try:
        result = subprocess.run(cmd, check=False)
        if result.returncode != 0:
            logMsg.warn(f'{subcommand} exited with non-zero return code: {result.returncode}')
            return False
        return True
    except Exception as e:
        logMsg.error(f'Unexpected error running {subcommand}: {e}')
        return False

# -- tideIndex: returns True if the Tide peptide index was built successfully, False on failure
def tideIndex(crux_bin, database, index_dir, config):
    logMsg.debug(f'Starting tide-index for database: {database.name}')
    args = [
        '--verbosity', '40',
        '--memory-limit', '8',
        '--enzyme', 'trypsin',
        '--digestion', 'full-digest',
        '--missed-cleavages', str(config['search']['missed_cleavages']),
        '--mods-spec', config['search']['mods_spec'],
        '--nterm-peptide-mods-spec', config['search']['nterm_peptide_mods_spec'],
        '--nterm-protein-mods-spec', config['search']['nterm_protein_mods_spec'],
        '--decoy-format', 'peptide-reverse',
        '--num-decoys-per-target', '1',
        '--allow-dups', 'T',
        '--clip-nterm-methionine', 'T',
        '--output-dir', str(index_dir),
        '--overwrite', 'T',
        str(database),
        str(index_dir),
    ]
    with _cleanBinaryFasta(index_dir):
        return runCrux(crux_bin, 'tide-index', args)

# -- paramMedic: returns True if param-medic completed successfully, False on failure
def paramMedic(crux_bin, mzml_file, out_dir):
    logMsg.debug(f'Running param-medic on: {mzml_file.name}')
    args = [
        '--verbosity', '40',
        '--output-dir', str(out_dir),
        str(mzml_file),
    ]
    return runCrux(crux_bin, 'param-medic', args)

# -- tideSearch: returns True if Tide-search completed successfully for the given mzML file, False on failure
def tideSearch(crux_bin, mzml_file, index_dir, out_dir, fileroot, config, precursor_tol=None, mz_bin_width=None):
    logMsg.debug(f'Starting tide-search for: {mzml_file.name}')
    prec = precursor_tol or config['search']['precursor_tolerance_ppm']
    bin_width = mz_bin_width  or config['search']['mz_bin_width']
    logMsg.debug(f'Using precursor tolerance: {prec} ppm, m/z bin width: {bin_width}')
    args = [
        '--verbosity', '40',
        '--num-threads', str(config['search']['threads']),
        '--spectrum-parser', 'pwiz',
        '--precursor-window', str(prec),
        '--precursor-window-type', 'ppm',
        '--mz-bin-width', str(bin_width),
        '--score-function', config['search']['score_function'],
        '--min-peaks', str(config['search']['min_peaks']),
        '--missed-cleavages', str(config['search']['missed_cleavages']),
        '--output-dir', str(out_dir),
        '--fileroot', fileroot,
        '--overwrite', 'T',
        str(mzml_file),
        str(index_dir),
    ]
    return runCrux(crux_bin, 'tide-search', args)

# -- percolator: returns True if Percolator rescoring completed successfully, False on failure
def percolator(crux_bin, target_psm_file, database, out_dir, fileroot, config):
    logMsg.debug(f'Starting Percolator for: {target_psm_file.name}')
    args = [
        '--verbosity', '40',
        '--protein-enzyme', config['percolator']['protein_enzyme'],
        '--spectral-counting-fdr', str(config['percolator']['psm_fdr']),
        '--output-dir', str(out_dir),
        '--fileroot', fileroot,
        '--overwrite', 'T',
        str(target_psm_file),
    ]
    if config['percolator']['picked_protein']:
        args = ['--picked-protein', str(database)] + args
    return runCrux(crux_bin, 'percolator', args)

# -- spectralCounts: returns True if dNSAF spectral counting completed successfully, False on failure
def spectralCounts(crux_bin, psm_file, database, out_dir, fileroot, config):
    logMsg.debug(f'Starting spectral-counts for: {psm_file.name}')
    args = [
        '--verbosity', '40',
        '--measure', config['quantify']['measure'],
        '--threshold', str(config['quantify']['qvalue_threshold']),
        '--threshold-type', 'qvalue',
        '--unique-mapping', 'T' if config['quantify']['unique_mapping'] else 'F',
        '--protein-database', str(database),
        '--output-dir', str(out_dir),
        '--fileroot', fileroot,
        '--overwrite', 'T',
        str(psm_file),
    ]
    with _cleanBinaryFasta(out_dir):
        return runCrux(crux_bin, 'spectral-counts', args)